### ISSUE TITLE
Meteor integration

### ISSUE THREAD

**Issue by jamc92** [mercadopago/sdk-nodejs#11]
Hi there, developers!

I'm trying to integrate the sdk-nodejs with Meteorjs.

Meteorjs is based on Node.js but I haven't had any success trying it by myself.

Do you have any suggestion about it?

**Comment by andruli** [comment]
Hey @jamc92 , have you found a meteor wrap of this library?

**Comment by jamc92** [comment]
Thanks for your answer @andruli . Not yet.

I haven't tried anymore but I have it on mind, so I can find a solution.

**Comment by n370** [comment]
https://github.com/HA-Team/meteor-mercadopago
