### ISSUE TITLE
The JS library that is in the Docs is broken

### ISSUE THREAD

**Issue by cavi21** [mercadopago/sdk-nodejs#12]
Hey guys, trying to implement the custom checkout and the library that is the in **[docs](http://labs.mercadopago.com.ar/developers/es/tools/sdk/client/javascript/)** have issues when calling **[#getPaymentMethod](http://labs.mercadopago.com.ar/developers/es/tools/sdk/client/javascript/#get-pm-info)** with a bin, I'm doing the call this way:
```javascript
Mercadopago.getPaymentMethod( { "bin": '4509 9535' }, MP.setPaymentMethodInfo)
```
And I'm getting this error:
```javascript
TypeError: b.bin is undefined
k.validateBinPattern()mercadopago.js (line 1)
l()mercadopago.js (line 1)
l()mercadopago.js (line 1)
k.getPaymentMethod()
```

There are a few other stuff that's weird like the **[docs](http://labs.mercadopago.com.ar/developers/es/tools/sdk/client/javascript/)** mention to load this library:
```html
<script src="https://secure.mlstatic.com/sdk/javascript/v1/mercadopago.js"></script>
```
And in all of your examples in **[here](https://github.com/mercadopago/code-examples)** you are loading this library:
```html
<script type="text/javascript" src="https://secure.mlstatic.com/org-img/checkout/custom/1.0/checkout.js"></script>
```
Also have a hard time trying to contact with anyone in there through the email developers@mercadopago.com is there a way to contact anyone a little bit more quickly for this kind of things? also in order to move the implementation to production?
Thanks!

**Comment by sebagun** [comment]
@cavi21 you should send the bin as first six digits only, without blank spaces:
```
Mercadopago.getPaymentMethod( { "bin": '450995' }, MP.setPaymentMethodInfo)
```
Please use 
```
<script src="https://secure.mlstatic.com/sdk/javascript/v1/mercadopago.js"></script>
```
as your SDK source. The other that you may see in that repo, has sense in examples for previous integrations, not yours.

Regards

**Comment by cavi21** [comment]
Hi @sebagun thanks a lot for the response! Ok about the library, but the issue is not being with the length of the bin, because I tried that (and again after your response) and throw the same error. Also checking the code in the JS library it seems that you are slice in it though
```javascript
k.validateBinPattern = function(a, b) {
        var c = a.slice(0, 6);
        return !((c.match(b.bin.pattern) ? 0 : 1) || b.bin.exclusion_pattern && c.match(b.bin.exclusion_pattern))
},[...]
```

**Comment by cavi21** [comment]
Ok, I think I narrowed down to the call of the methods **#l(a, b)** that it's called in:
```javascript
k.getPaymentMethod = function (a, b) {
  var c = a.bin || a.payment_method_id;
  return c ? (a.bin && (a.bin = d.clear(a.bin).replace(/[^0-9]/g, '').slice(0, 6)), g && g[c] ? 'function' == typeof b ? b(200, g[c])  : null : l(a, b))  : 'function' == typeof b ? b(400, {
    status: 400,
    error: 'bad_request',
    cause: {
      code: '2000',
      description: 'the payment_method_id or bin are required'
    }
  }, a)  : null
},
```

In there the ```k.validateBinPattern``` method is called 2 times the first one I think that's correct and the arguments is the object of the (in this case) **Visa Payment Method**:
```javascript
 {     
  bin: {
    exclusion_pattern "^(487017)"
    installments_pattern "^4"
    pattern "^4"
  }
  card_number: {
    length 16
    validation "standard"
  }
  security_code: {
    card_location "back"
    length 3
    mode "mandatory"
  }
}
```

and the second time is called with `unknown function(from, to)`

any idea @sebagun ?

**Comment by cavi21** [comment]
Hey guys, hope you don't take this in a bad way, because the only purpose is to try help and improve.

I went to the "Developer Conference" 2 weeks ago, and despite the fact that it was more focused like a "Partner Conference", in there you had the opportunity to present a bunch of nice features not only in MercadoPago but also other products. One of them was the **[custom checkout](http://labs.mercadopago.com.ar/developers/es/solutions/payments/custom-checkout/get-started/)**, that is the one that I'm struggling with in this particular case. 

There aren't smooth channels for communication, nor the usual ones that we have with other **products**, or **services**. In which there are several ways to communicate, sometimes an IRC channel (or a Slack, Hipchat room), also a status.io page, a help desk, and also very responsive to support emails. What I'm trying to say is that the service/product that you provide is not for free, so feels weird the unsupported or unresponsive that you are to sometimes PR or Issues across different of your repos.

Not trying to point to anyone, because I imagine that each one of you has a lot on their plates, but if there is no time to maintain a public repo of your own why don't you try to support other repos that are? just an idea.

I'm happy to help on anything I can, but it's frustrating and hard to do it if there is anyone on the other side.

Again, hope you take this in the good way
Have a nice week
