### ISSUE TITLE
Getting a payment

### ISSUE THREAD

**Issue by chamini2** [mercadopago/sdk-nodejs#26]
I was trying to use `getPayment` to get a payment information when receiving a webhook, but it does not work properly.

I found the [the actual request](https://github.com/mercadopago/sdk-nodejs/blob/13a0fa2237ee950e3beb66a16821081848f17189/lib/mercadopago.js#L410) is

```js
  return mp.get ({
    "uri": uriPrefix+"/collections/notifications/"+id
  }, next);
```

Shouldn't it be

```js
  return mp.get ({
    "uri": uriPrefix+"/payments/"+id
  }, next);
```

**Comment by arielfr** [comment]
@chamini2 The value received by the webhook is the Notification ID not the payment id. The notifications are used for:

- payments
- mp-connect
- plan
- suscription
- invoice

If you have more than 1 service (payment), you will receive all the events on that webhook. When you receive a notification you have a "topic" element on the response. The "topic" will tell you if it is a payment, invoice, etc... With /collection/notifications you get the "payload" of the notification, and with the topic you know what is going to be.

**Comment by chamini2** [comment]
Ok, this was unexpected. I would have expected a name like `getNotificationPayment`, and maybe the same for other _topics_: `getNotificationPlan`, `getNotificaitonSubscription`, etc.

**Comment by arielfr** [comment]
@chamini2 There is a new version of the SDK if you want to migrate the code. It is in BETA mode: https://github.com/mercadopago/px-nodejs
