### ISSUE TITLE
[Not an actual issue] Are client libs open source?

### ISSUE THREAD

**Issue by ascoppa** [mercadopago/sdk-nodejs#27]
I would like to have a look at the [javascript client code](https://secure.mlstatic.com/sdk/javascript/v1/mercadopago.js), but I couldn't found a link to the unminified (dev version) source. 

**I know this doesn't belong here but I wasn't sure where to put this given there's no repo for the JS client.**

Best,
Alfredo

**Comment by arielfr** [comment]
Yes, (here)[https://secure.mlstatic.com/sdk/javascript/v1/mercadopago.debug.js].

Cheers!
