### ISSUE TITLE
Sandbox no funciona

### ISSUE THREAD

**Issue by lainz** [mercadopago/sdk-nodejs#30]
Hola, con el siguiente código puedo llegar a la página de pago, pero cuando intento realizar el pago me rechazan la tarjeta, y estoy usando la que ustedes proveen en el sitio sandbox. Intenté cambiando el mail por uno real pero llego siempre al mismo error (imagen adjunta). Tengo configurado correctamente client id y client secret, en este caso los removí para mostrarles el código.

```
'use strict';

export function pagos(req, res) {
  var MP = require("mercadopago");
  // client id, client secret
  // https://www.mercadopago.com/mla/herramientas/aplicaciones
  var mp = new MP("", "");
  var preference = {};

  var item = {
    id: '0001',
    title: 'Pago mensual de POSBerry',
    quantity: 1,
    currency_id: 'ARS',
    unit_price: 400
  }

  var payer = {
    email: "test@test.com"
  }

  preference.items = [item]
  preference.payer = payer

  mp.createPreference(preference).then(function (data) {
    console.log(data)
     res.send(`
     <!DOCTYPE html>
     <html>
         <head>
             <title>Pagar</title>
         </head>
         <body>
             <a href="${data.response.sandbox_init_point}">Pagar</a>
         </body>
     </html>
     `);
   }).catch(function (error) {
    res.send(`
    <!DOCTYPE html>
    <html>
        <head>
            <title>Pagar</title>
        </head>
        <body>
            Error: no se procesó el pago.
        </body>
    </html>
    `);
   });
}
```

![sandbox](https://user-images.githubusercontent.com/4131395/31320445-13c6dd8a-ac4b-11e7-9267-597d2ef44983.png)

Me interesa implementar primero el pago y recibir la notificación IPN, esto es lo que tengo hasta ahora, pero nunca llegué a testearlo porque no puedo efectuar el pago en modo sandbox. De todos modos he configurado la URL y recibo la notificacion al darla de alta, pero necesito probar actualmente con una compra.

```
'use strict';
// configurar URL notificacion
// https://www.mercadopago.com.ar/ipn-notifications

export function notificaciones(req, res) {
    var MP = require("mercadopago");
    // client id, client secret
    // https://www.mercadopago.com/mla/herramientas/aplicaciones
    var mp = new MP("", "");

    mp.getPayment(req.body.id).then(
        function success(data) {
            console.log(JSON.stringify(data, null, 4));
        },
        function error(err) {
            console.log(err);
        }
    );
    res.sendStatus(200);
}
```

**Comment by arielfr** [comment]
Hola @lainz 

Con el ejemplo que me pasaste pude realizar un pago. Por las dudas, con tu usuario de MercadoPago que usas para poner el "client_id" y "client_secret" create un usuario de prueba. Pode ver como acá:

- https://www.mercadopago.com.ar/developers/es/solutions/payments/basic-checkout/test/test-users/

Una vez creado el usuario de prueba, fijate el mail con el cual se creo, que debería ser algo asi `test_user_3931...@testuser.com`. Este mail tenes que usarlo como mail del payer. Es decir, en lugar de test@test.com, pone el del usuario de prueba.

Después generas el link y pones la tarjeta de Prueba del siguiente link con el cardholdername = APRO.

- https://www.mercadopago.com.ar/developers/es/related/test-payments/

Si tu usuario de MP es de Argentina, usa la Visa de Argentina, si tu usuario es de Brasil, la tarjeta de Brasil, etc...

Debería andarte

**Comment by lainz** [comment]
Si pudiste entonces esta bien mi código, me faltó eso de los usuarios de prueba. Muchas gracias por tu tiempo.

**Comment by arielfr** [comment]
Si, el código esta perfecto ;)

**Comment by lainz** [comment]
Pude crear el usuario de prueba, uso la tarjeta de prueba y APRO en el nombre pero me dice "Los usuarios son inválidos."

**Comment by lainz** [comment]
Listo, tenian que ser los dos de prueba, también los numeros de la API.

**Comment by arielfr** [comment]
Exacto!, genial! :D

**Comment by lainz** [comment]
Una pregunta mas, la notificacion IPN no me llego enseguida, no sabes si tarda mucho mas, es que la recibo en localhost via un local tunnel, para poder ver que me devuelve y despues como poder trabajarlo.

**Comment by arielfr** [comment]
Los IPN no funcionan bien en modo sandbox :S

**Comment by lainz** [comment]
Listo, gracias, ya lo pude solucionar.
